# Generated by Django 6.0 on 2026-06-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Books', 'Books'), ('Accessories', 'Accessories')], default='Electronics', max_length=20),
        ),
    ]
